### ISSUE TITLE
Doesn't work at all :<

### ISSUE THREAD

**Issue by Wjxfi** [Myzel394/kleckrelay-website#26]
![](https://files.catbox.moe/zh721o.jpg)

**Comment by Myzel394** [comment]
Oh hi @Wjxfi,

I'm sorry, but KleckRelay is kinda on ice. I am currently not able to pay monthly for a server that is capable of handling active users. That's one reason why I'm currently focusing on app development. I might continue KleckRelay in the future, but I'm not sure when. Sorry about that :(

**Comment by Myzel394** [comment]
For the moment, if you are searching for alternatives, you can try out DuckDuckGo's Email Tracking Protection or SimpleLogin - though I'd prefer DuckDuckGo much more. SimpleLogin isn't end-to-end encrypted and has a limit on aliases. Also, I have spoken to the CEO of SimpleLogin once and... well I don't wanna be rude but he wasn't the nicest person to speak to.
